version: 0.2

phases:


  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 289525298288.dkr.ecr.ap-northeast-1.amazonaws.com


  build:
    commands:
      - docker build -t housebook_front front/.
      - docker tag housebook_front:latest 289525298288.dkr.ecr.ap-northeast-1.amazonaws.com/housebook_front:latest
      

  post_build:
    commands:
      - docker push 289525298288.dkr.ecr.ap-northeast-1.amazonaws.com/housebook_front:latest


