version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - yum update -y
      - yum install -y docker
      - docker --version

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 289525298288.dkr.ecr.ap-northeast-1.amazonaws.com
      - export REPOSITORY_URI_DB=289525298288.dkr.ecr.ap-northeast-1.amazonaws.com/housebook_db
      - export REPOSITORY_URI_APP=289525298288.dkr.ecr.ap-northeast-1.amazonaws.com/housebook_app
      - export REPOSITORY_URI_FRONT=289525298288.dkr.ecr.ap-northeast-1.amazonaws.com/housebook_front
      - export REPOSITORY_URI_WEB=289525298288.dkr.ecr.ap-northeast-1.amazonaws.com/housebook_web

  build:
    commands:
      - echo Build phase...
      - docker build -t do -f do/Dockerfile .
      - docker build -t app -f app/Dockerfile .
      - docker build -t front -f front/Dockerfile .
      - docker build -t web -f web/Dockerfile .

  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker tag do:latest $REPOSITORY_URI_DB:do_latest
      - docker tag app:latest $REPOSITORY_URI_APP:app_latest
      - docker tag front:latest $REPOSITORY_URI_FRONT:front_latest
      - docker tag web:latest $REPOSITORY_URI_WEB:web_latest

      - docker push $REPOSITORY_URI_DB:do_latest
      - docker push $REPOSITORY_URI_APP:app_latest
      - docker push $REPOSITORY_URI_FRONT:front_latest
      - docker push $REPOSITORY_URI_WEB:web_latest

      - echo Images pushed to ECR
