version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com

build-graph:
  phases:
    - identifier: build_app
      buildspec: buildspec_app.yml
    - identifier: build_front
      buildspec: buildspec_front.yml
      depends-on:
        - build_app
    - identifier: build_web
      buildspec: buildspec_web.yml
      depends-on:
        - build_front
