version: 0.2

batch:
  build-graph:
    - identifier: build_app
      buildspec: buildspec_app.yml
    - identifier: build_front
      buildspec: buildspec_front.yml
      depends-on:
        - build_app
    - identifier: build_web
      buildspec: buildspec_web.yml
      depends-on:
        - build_front

artifacts:
  files:
    - appspec.yaml
