version: '3.1'

services:
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expenses
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/go/src
    tty: true
    ports:
      - "8080:8080"
      - "2345:2345" 
    depends_on:
      - db

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/src:/app/src
    ports:
      - '3000:3000'

  local:
    container_name: local
    build:
      context: ./local
      dockerfile: Dockerfile
    ports:
      - 443:443

volumes:
  db_data: