version: '3'
services:
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expenses
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    depends_on:
      - app
  web:
    container_name: nginx
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - front


volumes:
  db_data: