# ベースイメージを指定
FROM node:14-alpine

# 作業ディレクトリを設定
WORKDIR /app

# プロジェクトの依存関係をコピー
COPY ./front/package.json ./front/package-lock.json ./

# 依存関係のインストール
RUN npm install

# プロジェクトファイルをコピー
# COPY ./front/. .

# アプリを起動
RUN npm run dev

# ポートを指定
# EXPOSE 3000

# # アプリを起動
# CMD ["npm", "start"]
