CREATE DATABASE IF NOT EXISTS expenses;

USE expenses;

CREATE TABLE IF NOT EXISTS expenses (
    id INT AUTO_INCREMENT,
    category VARCHAR(255) NOT NULL,
    amount VARCHAR(255) NOT NULL,
    memo VARCHAR(255),
    date VARCHAR(255) NOT NULL,
    sort_at VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

